import { type ClassValue, clsx } from "clsx";
import { twMerge } from "tailwind-merge";

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs));
}

export const teamConfig = {
  "red-team": {
    label: "Red Team",
    shortLabel: "RED",
    color: "#ef4444",
    bgClass: "bg-red-500/10",
    borderClass: "border-red-500/30",
    textClass: "text-red-400",
    glowClass: "shadow-[0_0_20px_rgba(239,68,68,0.3)]",
    badgeClass: "bg-red-500/20 text-red-300 border-red-500/30",
    gradient: "from-red-900/20 to-transparent",
    description: "Ofansif Güvenlik — Saldırı tekniklerini öğren, savunmayı güçlendir",
  },
  "blue-team": {
    label: "Blue Team",
    shortLabel: "BLUE",
    color: "#3b82f6",
    bgClass: "bg-blue-500/10",
    borderClass: "border-blue-500/30",
    textClass: "text-blue-400",
    glowClass: "shadow-[0_0_20px_rgba(59,130,246,0.3)]",
    badgeClass: "bg-blue-500/20 text-blue-300 border-blue-500/30",
    gradient: "from-blue-900/20 to-transparent",
    description: "Defansif Güvenlik — Tehditleri tespit et, sistemleri koru",
  },
  "purple-team": {
    label: "Purple Team",
    shortLabel: "PURPLE",
    color: "#a855f7",
    bgClass: "bg-purple-500/10",
    borderClass: "border-purple-500/30",
    textClass: "text-purple-400",
    glowClass: "shadow-[0_0_20px_rgba(168,85,247,0.3)]",
    badgeClass: "bg-purple-500/20 text-purple-300 border-purple-500/30",
    gradient: "from-purple-900/20 to-transparent",
    description: "Senkronizasyon — Red ve Blue'yu birleştir, güvenlik döngüsünü kapat",
  },
  "network-fundamentals": {
    label: "Network",
    shortLabel: "NET",
    color: "#10b981",
    bgClass: "bg-emerald-500/10",
    borderClass: "border-emerald-500/30",
    textClass: "text-emerald-400",
    glowClass: "shadow-[0_0_20px_rgba(16,185,129,0.3)]",
    badgeClass: "bg-emerald-500/20 text-emerald-300 border-emerald-500/30",
    gradient: "from-emerald-900/20 to-transparent",
    description: "Network — Temelden CCNA seviyesine: OSI, Cisco IOS, VLAN, Routing, Güvenlik",
  },
  "linux-fundamentals": {
    label: "Linux Eğitimi",
    shortLabel: "LINUX",
    color: "#f97316",
    bgClass: "bg-orange-500/10",
    borderClass: "border-orange-500/30",
    textClass: "text-orange-400",
    glowClass: "shadow-[0_0_20px_rgba(249,115,22,0.3)]",
    badgeClass: "bg-orange-500/20 text-orange-300 border-orange-500/30",
    gradient: "from-orange-900/20 to-transparent",
    description: "Linux Temelden İleriye — Terminal, Dosya Sistemi, Sistem Yönetimi",
  },
  "windows-fundamentals": {
    label: "Windows Eğitimi",
    shortLabel: "WIN",
    color: "#0ea5e9",
    bgClass: "bg-sky-500/10",
    borderClass: "border-sky-500/30",
    textClass: "text-sky-400",
    glowClass: "shadow-[0_0_20px_rgba(14,165,233,0.3)]",
    badgeClass: "bg-sky-500/20 text-sky-300 border-sky-500/30",
    gradient: "from-sky-900/20 to-transparent",
    description: "Windows Temelden İleriye — CMD, PowerShell, Sistem Yönetimi",
  },
  "owasp-top10": {
    label: "OWASP Top 10",
    shortLabel: "OWASP",
    color: "#f59e0b",
    bgClass: "bg-amber-500/10",
    borderClass: "border-amber-500/30",
    textClass: "text-amber-400",
    glowClass: "shadow-[0_0_20px_rgba(245,158,11,0.3)]",
    badgeClass: "bg-amber-500/20 text-amber-300 border-amber-500/30",
    gradient: "from-amber-900/20 to-transparent",
    description: "OWASP Top 10 — Web Uygulama Güvenliğinin En Kritik Zafiyetleri",
  },
  "devops-fundamentals": {
    label: "DevOps Temelleri",
    shortLabel: "DEVOPS",
    color: "#14b8a6",
    bgClass: "bg-teal-500/10",
    borderClass: "border-teal-500/30",
    textClass: "text-teal-400",
    glowClass: "shadow-[0_0_20px_rgba(20,184,166,0.3)]",
    badgeClass: "bg-teal-500/20 text-teal-300 border-teal-500/30",
    gradient: "from-teal-900/20 to-transparent",
    description: "DevOps Temelleri — Git ve Docker ile modern mühendislik komut alışkanlıkları",
  },
  "certifications": {
    label: "Sertifikalar",
    shortLabel: "CERT",
    color: "#6366f1",
    bgClass: "bg-indigo-500/10",
    borderClass: "border-indigo-500/30",
    textClass: "text-indigo-400",
    glowClass: "shadow-[0_0_20px_rgba(99,102,241,0.3)]",
    badgeClass: "bg-indigo-500/20 text-indigo-300 border-indigo-500/30",
    gradient: "from-indigo-900/20 to-transparent",
    description: "Sertifikalar — Security+, OSCP, CISSP ve kariyer yol haritası",
  },
  "ecosystem": {
    label: "Sektör & Ekosistem",
    shortLabel: "SEKTÖR",
    color: "#ec4899",
    bgClass: "bg-pink-500/10",
    borderClass: "border-pink-500/30",
    textClass: "text-pink-400",
    glowClass: "shadow-[0_0_20px_rgba(236,72,153,0.3)]",
    badgeClass: "bg-pink-500/20 text-pink-300 border-pink-500/30",
    gradient: "from-pink-900/20 to-transparent",
    description: "Sektör & Ekosistem — Ürünler, şirketler, önemli kişiler ve kavramlar",
  },
  "servers-fundamentals": {
    label: "Sunucular",
    shortLabel: "SRV",
    color: "#06b6d4",
    bgClass: "bg-cyan-500/10",
    borderClass: "border-cyan-500/30",
    textClass: "text-cyan-400",
    glowClass: "shadow-[0_0_20px_rgba(6,182,212,0.3)]",
    badgeClass: "bg-cyan-500/20 text-cyan-300 border-cyan-500/30",
    gradient: "from-cyan-900/20 to-transparent",
    description: "Sunucular — Nedir, nasıl yönetilir ve nasıl sızılır (Linux/Windows/Web)",
  },
  "database-fundamentals": {
    label: "Veritabanları",
    shortLabel: "DB",
    color: "#84cc16",
    bgClass: "bg-lime-500/10",
    borderClass: "border-lime-500/30",
    textClass: "text-lime-400",
    glowClass: "shadow-[0_0_20px_rgba(132,204,22,0.3)]",
    badgeClass: "bg-lime-500/20 text-lime-300 border-lime-500/30",
    gradient: "from-lime-900/20 to-transparent",
    description: "Veritabanları — SQL/NoSQL, komutlar, yönetim ve nasıl sızılır",
  },
  "metodoloji": {
    label: "Metodoloji",
    shortLabel: "METOD",
    color: "#d946ef",
    bgClass: "bg-fuchsia-500/10",
    borderClass: "border-fuchsia-500/30",
    textClass: "text-fuchsia-400",
    glowClass: "shadow-[0_0_20px_rgba(217,70,239,0.3)]",
    badgeClass: "bg-fuchsia-500/20 text-fuchsia-300 border-fuchsia-500/30",
    gradient: "from-fuchsia-900/20 to-transparent",
    description: "Metodoloji — Pentest sürecinin omurgası: araçları değil, düşünme biçimini öğren",
  },
} as const;

export const riskConfig = {
  low:      { label: "Düşük Risk",    class: "bg-green-500/10 text-green-400 border-green-500/20" },
  medium:   { label: "Orta Risk",     class: "bg-yellow-500/10 text-yellow-400 border-yellow-500/20" },
  high:     { label: "Yüksek Risk",   class: "bg-orange-500/10 text-orange-400 border-orange-500/20" },
  critical: { label: "Kritik Risk",   class: "bg-red-500/10 text-red-400 border-red-500/20" },
} as const;

export const difficultyConfig = {
  beginner: { label: "Başlangıç", class: "badge-beginner", order: 0 },
  intermediate: { label: "Orta Seviye", class: "badge-intermediate", order: 1 },
  advanced: { label: "İleri Seviye", class: "badge-advanced", order: 2 },
} as const;
